# Generated by Django 5.1.5 on 2025-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='key_details',
            field=models.TextField(blank=True),
        ),
    ]
