# Generated by Django 5.1.5 on 2025-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_review_watchagain_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('movie_name', 'year'), name='unique_movie_request')],
            },
        ),
    ]
